### ISSUE TITLE
Error when executing: The system cannot find the file specified

### ISSUE THREAD

**Issue by redknightlois** [PerfDotNet/BenchmarkDotNet#10]
Check that the first time called the error is "The system cannot find the file specified" and the directory is created, but when run the second time the error is different and then the directory is deleted.

Available competitions:
  #0 Program

You should select the target benchmark. Please, print a number of a becnhmark (e.g. #0) or a benchmark caption:
#0

Target competition: Program
// ***** Competition: Start   *****
// Found benchmarks:
//   Program_Alternative_Throughput_CurrentPlatform_CurrentJit_NET-Current -w=5 -t=10
//   Program_Current_Throughput_CurrentPlatform_CurrentJit_NET-Current -w=5 -t=10

// **************************
// Benchmark: Program_Alternative (Throughput_CurrentPlatform_CurrentJit_NET-Current) [-w=5 -t=10]
// Generated project: D:\Repositories\ravendbgit\Raven.Tryouts\bin\Release\Program_Alternative_Throughput_CurrentPlatform_CurrentJit_NET-Current

// Build:

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BenchmarkDotNet.BenchmarkExecutor.Exec(String exeName, String args)
   at BenchmarkDotNet.BenchmarkProjectGenerator.CompileCode(String directoryPath)
   at BenchmarkDotNet.BenchmarkRunner.Run(Benchmark benchmark, IList`1 importantPropertyNames)
   at BenchmarkDotNet.BenchmarkRunner.RunCompetition(List`1 benchmarks)
   at BenchmarkDotNet.BenchmarkCompetitionSwitch.RunCompetitions(String[] args)
   at Raven.Tryouts.Program.Main(String[] args) in d:\Repositories\ravendb-git\Raven.Tryouts\Program.cs:line 229
PS D:\Repositories\ravendb-git\Raven.Tryouts\bin\Release> .\Raven.Tryouts.exe
Available competitions:
  #0 Program

You should select the target benchmark. Please, print a number of a becnhmark (e.g. #0) or a benchmark caption:
#0

Target competition: Program
// ***** Competition: Start   *****
// Found benchmarks:
//   Program_Alternative_Throughput_CurrentPlatform_CurrentJit_NET-Current -w=5 -t=10
//   Program_Current_Throughput_CurrentPlatform_CurrentJit_NET-Current -w=5 -t=10

// **************************
// Benchmark: Program_Alternative (Throughput_CurrentPlatform_CurrentJit_NET-Current) [-w=5 -t=10]

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Repositories\ravendb-gi
t\Raven.Tryouts\bin\Release\Program_Alternative_Throughput_CurrentPlatform_CurrentJit_NET-Current\Program.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShar
e share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileO
ptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at BenchmarkDotNet.BenchmarkProjectGenerator.GenerateProgramFile(String projectDir, Benchmark benchmark)
   at BenchmarkDotNet.BenchmarkProjectGenerator.GenerateProject(Benchmark benchmark)
   at BenchmarkDotNet.BenchmarkRunner.Run(Benchmark benchmark, IList`1 importantPropertyNames)
   at BenchmarkDotNet.BenchmarkRunner.RunCompetition(List`1 benchmarks)
   at BenchmarkDotNet.BenchmarkCompetitionSwitch.RunCompetitions(String[] args)
   at Raven.Tryouts.Program.Main(String[] args) in d:\Repositories\ravendb-git\Raven.Tryouts\Program.cs:line 229
PS D:\Repositories\ravendb-git\Raven.Tryouts\bin\Release>

**Comment by AndreyAkinshin** [comment]
@redknightlois, please, try new version of the library: v0.7.5

**Comment by redknightlois** [comment]
Now it works. Thanks.
