### ISSUE TITLE
Unable to run using 0.9.3-beta (DNX 5.0)

### ISSUE THREAD

**Issue by rold2007** [PerfDotNet/BenchmarkDotNet#127]
I tried to use the beta version of BenchmarkDotNet using DNX but it doesn't work even on the most basic example. Here is my sample code: [ConsoleApp.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/185575/ConsoleApp.zip)

When I run it I have the following exception:
_System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliBuilder.ExecuteCommand(String commandWithArguments, String workingDirectory, ILogger logger)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliBuilder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark)
   at BenchmarkDotNet.Running.BenchmarkRunner.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark benchmark, ILogger logger, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\david\documents\visual studio 2015\Projects\ConsoleApp1\Program.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()_

I tried to compile BenchmarkDotNet in debug to see what was the problem but then I get a different exception which seems to be related to a missing assembly: System.Runtime.InteropServices.PInvoke.

DNX is pretty new to me so maybe I'm doing something wrong.

**Comment by adamsitnik** [comment]
Hi @rold2007 Do you have dotnet cli toolchain installed?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, can we detect a situation when user doesn't have installed dotnet cli and print warning?

**Comment by adamsitnik** [comment]
@AndreyAkinshin sure, I will implement this

**Comment by rold2007** [comment]
Thanks for your help, now it works !
If anyone has the same problem, just follow the instruction [here](https://dotnet.github.io/getting-started/).

**Comment by adamsitnik** [comment]
@rold2007 You welcome! I am very happy that you use it, you are proably one of the first people that use dnxcore50 support! Please let me know if you have any troubles.
