### ISSUE TITLE
No more Benchmark runs will be launched as NO measurments were obtained from the previous run!

### ISSUE THREAD

**Issue by JimBobSquarePants** [PerfDotNet/BenchmarkDotNet#139]
Hi there,

I've been attempting to run some test which require retrieving objects via indexers using unsafe code and I keep getting a crash with the above error message.

I don't know whether I have done something daft or whether it is an actual bug. I was able to run the tests successfully without a for-loop in each test but as soon as I added it the error occurred.

I've attached the full program for you to look at. [BenchmarkTest.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/205650/BenchmarkTest.zip)

Here's the full output.

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   ImagePerformance_FixedImage
//   ImagePerformance_Image
//   ImagePerformance_UnsafeImage

// **************************
// Benchmark: ImagePerformance_FixedImage
// *** Generate ***
// Result = Success
// DirectoryPath = E:\projects\BenchmarkTest\BenchmarkTest\bin\Debug\ImagePerformance_FixedImage

// *** Build ***
// Result = Success

// *** Execute ***
// Launch: 1

// BenchmarkDotNet=v0.9.4.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
// Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
// JitModules=clrjit-v4.6.1063.1

No more Benchmark runs will be launched as NO measurments were obtained from the previous run!


// **************************
// Benchmark: ImagePerformance_Image
// *** Generate ***
// Result = Success
// DirectoryPath = E:\projects\BenchmarkTest\BenchmarkTest\bin\Debug\ImagePerformance_Image

// *** Build ***
// Result = Success

// *** Execute ***
// Launch: 1

// BenchmarkDotNet=v0.9.4.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
// Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
// JitModules=clrjit-v4.6.1063.1

Pilot 1: 4 op, 6754793.12 ns, 1.6887 ms/op
Pilot 2: 8 op, 11456011.09 ns, 1.4320 ms/op
Pilot 3: 16 op, 18486025.62 ns, 1.1554 ms/op
Pilot 4: 32 op, 38973019.96 ns, 1.2179 ms/op
Pilot 5: 64 op, 74998155.57 ns, 1.1718 ms/op
Pilot 6: 128 op, 149183798.5 ns, 1.1655 ms/op
Pilot 7: 256 op, 269298698.63 ns, 1.0519 ms/op

IdleWarmup 1: 256 op, 4170.02 ns, 16.2891 ns/op
IdleWarmup 2: 256 op, 1283.08 ns, 5.0120 ns/op
IdleWarmup 3: 256 op, 1283.08 ns, 5.0120 ns/op
IdleWarmup 4: 256 op, 1283.08 ns, 5.0120 ns/op
IdleWarmup 5: 256 op, 1283.08 ns, 5.0120 ns/op

IdleTarget 1: 256 op, 1283.08 ns, 5.0120 ns/op
IdleTarget 2: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 3: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 4: 256 op, 641.54 ns, 2.5060 ns/op
IdleTarget 5: 256 op, 1283.08 ns, 5.0120 ns/op
IdleTarget 6: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 7: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 8: 256 op, 1283.08 ns, 5.0120 ns/op
IdleTarget 9: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 10: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 11: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 12: 256 op, 962.31 ns, 3.7590 ns/op

MainWarmup 1: 256 op, 275782440.36 ns, 1.0773 ms/op
MainWarmup 2: 256 op, 280140112.72 ns, 1.0943 ms/op
MainWarmup 3: 256 op, 275329191.11 ns, 1.0755 ms/op
MainWarmup 4: 256 op, 277448203.52 ns, 1.0838 ms/op
MainWarmup 5: 256 op, 264202611.72 ns, 1.0320 ms/op
MainWarmup 6: 256 op, 264072378.74 ns, 1.0315 ms/op
MainWarmup 7: 256 op, 264158345.34 ns, 1.0319 ms/op

MainTarget 1: 256 op, 255985424.17 ns, 999.9431 us/op
MainTarget 2: 256 op, 253060956.09 ns, 988.5194 us/op
MainTarget 3: 256 op, 257033703.4 ns, 1.0040 ms/op
MainTarget 4: 256 op, 255984782.63 ns, 999.9406 us/op
MainTarget 5: 256 op, 265400049.4 ns, 1.0367 ms/op
MainTarget 6: 256 op, 253658231.46 ns, 990.8525 us/op
MainTarget 7: 256 op, 260092253.7 ns, 1.0160 ms/op
MainTarget 8: 256 op, 258236273.41 ns, 1.0087 ms/op
MainTarget 9: 256 op, 257013815.6 ns, 1.0040 ms/op
MainTarget 10: 256 op, 261612066.12 ns, 1.0219 ms/op

Result 1: 256 op, 255984461.86 ns, 999.9393 us/op
Result 2: 256 op, 253059993.78 ns, 988.5156 us/op
Result 3: 256 op, 257032741.08 ns, 1.0040 ms/op
Result 4: 256 op, 255983820.32 ns, 999.9368 us/op
Result 5: 256 op, 265399087.09 ns, 1.0367 ms/op
Result 6: 256 op, 253657269.15 ns, 990.8487 us/op
Result 7: 256 op, 260091291.39 ns, 1.0160 ms/op
Result 8: 256 op, 258235311.1 ns, 1.0087 ms/op
Result 9: 256 op, 257012853.29 ns, 1.0040 ms/op
Result 10: 256 op, 261611103.8 ns, 1.0219 ms/op

// Launch: 2

// BenchmarkDotNet=v0.9.4.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
// Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
// JitModules=clrjit-v4.6.1063.1

Pilot 1: 4 op, 5014290.34 ns, 1.2536 ms/op
Pilot 2: 8 op, 9692092.04 ns, 1.2115 ms/op
Pilot 3: 16 op, 19092924.12 ns, 1.1933 ms/op
Pilot 4: 32 op, 39833968.99 ns, 1.2448 ms/op
Pilot 5: 64 op, 78029119.58 ns, 1.2192 ms/op
Pilot 6: 128 op, 154505066.58 ns, 1.2071 ms/op
Pilot 7: 256 op, 283707405.64 ns, 1.1082 ms/op

IdleWarmup 1: 256 op, 3528.48 ns, 13.7831 ns/op
IdleWarmup 2: 256 op, 962.31 ns, 3.7590 ns/op
IdleWarmup 3: 256 op, 962.31 ns, 3.7590 ns/op
IdleWarmup 4: 256 op, 962.31 ns, 3.7590 ns/op
IdleWarmup 5: 256 op, 641.54 ns, 2.5060 ns/op
IdleWarmup 6: 256 op, 962.31 ns, 3.7590 ns/op

IdleTarget 1: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 2: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 3: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 4: 256 op, 1283.08 ns, 5.0120 ns/op
IdleTarget 5: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 6: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 7: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 8: 256 op, 962.31 ns, 3.7590 ns/op
IdleTarget 9: 256 op, 1283.08 ns, 5.0120 ns/op
IdleTarget 10: 256 op, 962.31 ns, 3.7590 ns/op

MainWarmup 1: 256 op, 277241306.31 ns, 1.0830 ms/op
MainWarmup 2: 256 op, 261515514.08 ns, 1.0215 ms/op
MainWarmup 3: 256 op, 268659402.28 ns, 1.0495 ms/op
MainWarmup 4: 256 op, 262592021.15 ns, 1.0258 ms/op
MainWarmup 5: 256 op, 268078165.45 ns, 1.0472 ms/op
MainWarmup 6: 256 op, 265471581.3 ns, 1.0370 ms/op
MainWarmup 7: 256 op, 271216908.47 ns, 1.0594 ms/op

MainTarget 1: 256 op, 257080856.71 ns, 1.0042 ms/op
MainTarget 2: 256 op, 257680056.71 ns, 1.0066 ms/op
MainTarget 3: 256 op, 263658584.31 ns, 1.0299 ms/op
MainTarget 4: 256 op, 260016551.78 ns, 1.0157 ms/op
MainTarget 5: 256 op, 256690157.79 ns, 1.0027 ms/op
MainTarget 6: 256 op, 260106367.62 ns, 1.0160 ms/op
MainTarget 7: 256 op, 259829863.13 ns, 1.0150 ms/op
MainTarget 8: 256 op, 257379494.4 ns, 1.0054 ms/op
MainTarget 9: 256 op, 261927704.66 ns, 1.0232 ms/op
MainTarget 10: 256 op, 260779024.15 ns, 1.0187 ms/op

Result 1: 256 op, 257079894.4 ns, 1.0042 ms/op
Result 2: 256 op, 257679094.4 ns, 1.0066 ms/op
Result 3: 256 op, 263657622 ns, 1.0299 ms/op
Result 4: 256 op, 260015589.46 ns, 1.0157 ms/op
Result 5: 256 op, 256689195.47 ns, 1.0027 ms/op
Result 6: 256 op, 260105405.31 ns, 1.0160 ms/op
Result 7: 256 op, 259828900.81 ns, 1.0150 ms/op
Result 8: 256 op, 257378532.09 ns, 1.0054 ms/op
Result 9: 256 op, 261926742.35 ns, 1.0232 ms/op
Result 10: 256 op, 260778061.84 ns, 1.0187 ms/op


Mean = 1.0104 ms, StdError = 0.0027 ms (0.27%); N = 20, StdDev = 0.0122 ms
Min = 0.9885 ms, Q1 = 1.0033 ms, Median = 1.0076 ms, Q3 = 1.0174 ms, Max = 1.0367 ms
IQR = 0.0140 ms, LowerFence = 0.9823 ms, UpperFence = 1.0384 ms
ConfidenceInterval = [1.0050 ms; 1.0158 ms] (CI 95%)


// **************************
// Benchmark: ImagePerformance_UnsafeImage
// *** Generate ***
// Result = Success
// DirectoryPath = E:\projects\BenchmarkTest\BenchmarkTest\bin\Debug\ImagePerformance_UnsafeImage

// *** Build ***
// Result = Success

// *** Execute ***
// Launch: 1

// BenchmarkDotNet=v0.9.4.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
// Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
// CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
// JitModules=clrjit-v4.6.1063.1

No more Benchmark runs will be launched as NO measurments were obtained from the previous run!



Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Columns.BaselineDiffColumn.GetValue(Summary summary, Benchmark benchmark)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass21_2.<.ctor>b__11(IColumn c)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass21_1.<.ctor>b__10(BenchmarkReport r)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, EnvironmentHelper hostEnvironmentHelper, IConfig config, String currentDirectory, TimeSpan totalTime)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at BenchmarkTest.Program.ImagePerformance.Main(String[] args) in E:\projects\BenchmarkTest\BenchmarkTest\Program.cs:line 19
```
 
Thanks!

p.s measurements is spelled incorrectly :wink:

**Comment by JimBobSquarePants** [comment]
Ughhhh :disappointed: I was mixing up `byte` and `float` in my code. Please ignore me and keep up the good work!

**Comment by mattwarren** [comment]
> p.s measurements is spelled incorrectly :wink:

Thanks for spotting that, just fixed it see d371de9 (the smallest commit I've ever done!!)

**Comment by adamsitnik** [comment]
@mattwarren Maybe we could extend this message with some hint? Like: "Most probably your benchmark method has bug and we have failed to measure it. Please verify that it is correct" ?

**Comment by JimBobSquarePants** [comment]
No worries ☺ It might be an idea. It's much more likely the error would be in the developers code and sometimes just a hint is enough to point you in the right direction.
