### ISSUE TITLE
Crash on [Params] with a string value that contains an invalid path char

### ISSUE THREAD

**Issue by HellBrick** [PerfDotNet/BenchmarkDotNet#148]
Here's a repro:
```csharp
	[Config( typeof( Config ) )]
	public class Program
	{
		private const char _charTofind = '*';

		internal static void Main( string[] args )
		{
			var summary = BenchmarkRunner.Run<Program>();
		}

		private class Config : ManualConfig
		{
			public Config()
			{
				Add( Job.Clr.WithLaunchCount( 1 ) );
			}
		}

		[Params( "*" )]
		public string Value { get; set; }

		[Benchmark( Baseline = true )]
		public int StringIndexOf() => Value.IndexOf( _charTofind );
	}
```
```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   Program_StringIndexOf_Runtime-Clr_Process1_Value-*

// **************************
// Benchmark: Program_StringIndexOf_Runtime-Clr_Process1_Value-*
// *** Generate ***

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at BenchmarkDotNet.Toolchains.GeneratorBase.CreateProjectDirectory(Benchmark benchmark)
   at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateProject(Benchmark benchmark, ILogger logger)
   at BenchmarkDotNet.Running.BenchmarkRunner.Generate(ILogger logger, IToolchain toolchain, Benchmark benchmark)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark benchmark, ILogger logger, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
```

**Comment by AndreyAkinshin** [comment]
Thanks for the report, will be fixed soon.

**Comment by adamsitnik** [comment]
@HellBrick Thanks for very well described bug report! The bug has been fixed and will be a part of the upcoming release.
