### ISSUE TITLE
Problem with ExceptionDispatchInfo

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#171]
_Sometimes_ some of our classic test fail with the following exception:

```
      System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
      Stack Trace:
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Lazy`1.get_Value()
        BenchmarkDotNet\Jobs\Job.cs(45,0): at BenchmarkDotNet.Jobs.Job.Equals(IJob other)
        BenchmarkDotNet\Jobs\JobExtensions.cs(105,0): at BenchmarkDotNet.Jobs.JobExtensions.TryGetShortInfoForPredefinedJobs(IJob job, String& shortInfo)
        BenchmarkDotNet\Jobs\JobExtensions.cs(53,0): at BenchmarkDotNet.Jobs.JobExtensions.GetShortInfo(IJob job, IJob[] allJobs)
        BenchmarkDotNet\Running\Benchmark.cs(14,0): at BenchmarkDotNet.Running.Benchmark.get_ShortInfo()
        BenchmarkDotNet\Running\BenchmarkRunner.cs(73,0): at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath)
        BenchmarkDotNet\Running\BenchmarkRunner.cs(50,0): at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark[] benchmarks, IConfig config)
        BenchmarkDotNet.IntegrationTests.Classic\ReferencesTests.cs(51,0): at BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.CanCompileAndRun[TBenchmark]()
      System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
```

List of tests with troubles:
```
Error: .NET 4.6 tests has failed:
    BenchmarkDotNet.IntegrationTests.Classic.AssemblyConfigTests.IsActivatedTest [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.VisualBasicIsSupported [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.BenchmarksThatReturnTypeThatRequiresDifferentRuntimeAreSupported [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.BenchmarksThatReturnTypeFromCustomPathDllAreSupported [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.BenchmarksThatUseTypeFromCustomPathDllAreSupported [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.BenchmarksThatUseTypeThatRequiresDifferentRuntimeAreSupported [FAIL]
    BenchmarkDotNet.IntegrationTests.Classic.ReferencesTests.FSharpIsSupported [FAIL]
```

**Comment by adamsitnik** [comment]
Another crazy bug! It is really strange because I usually run all our tests few times a day and it has never happened to me.. Anyway sorry for that, the blame is on me ;)
