### ISSUE TITLE
MSBuild dependency - best way of fixing?

### ISSUE THREAD

**Issue by jskeet** [PerfDotNet/BenchmarkDotNet#191]
I've managed to get the benchmarks running on my dev box, but on my CI machine I'm failing - when I run it (with `dotnet run`) I end up with an exception:

```text
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Toolchains.Classic.ClassicBuilder.Build(GenerateResult generateResult, ILogger logger, Benchmark benchmark)
   at BenchmarkDotNet.Running.BenchmarkRunner.Build(ILogger logger, IToolchain toolchain, GenerateResult generateResult, Benchmark benchmark)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark[] benchmarks, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args)
   at NodaTime.Benchmarks.Program.Main(String[] args) in C:\Users\Jon\NodaTime\nodatime\src\NodaTime.Benchmarks\Program.cs:line 17
```

I assume it needs the assemblies in the GAC, but I'm not sure of the least-impact way of doing that. Aside from anything else, something to add in the Getting Started section?

(The machine has VS 2015 installed as well as .NET Core RC2.)

**Comment by AndreyAkinshin** [comment]
We are going to drop MSBuild dependency in the next version. See also: https://github.com/PerfDotNet/BenchmarkDotNet/issues/149

**Comment by jskeet** [comment]
Okay - will leave this issue open so that if we *do* at least keep this toolchain as an option, we also document how to make it work.

**Comment by AndreyAkinshin** [comment]
Now you can try the following way: change TargetFramework of your project to 4.6 and reinstall BenchmarkDotNet. The dll from the `net46/` use MSBuild14.

**Comment by jskeet** [comment]
Yup, changing to use net46 in project.json seems to have sorted it. (Now I need to get it to use the Release config of Noda Time, but that's a separate matter...)
