### ISSUE TITLE
Regression in 0.9.7: --help option fails under dotnet run

### ISSUE THREAD

**Issue by jskeet** [PerfDotNet/BenchmarkDotNet#197]
With 0.9.6:

```
>dotnet run -c Release -- --help
[... build bits ...]

BenchmarkDotNet v0.9.6
Options:
  --jobs <JOBS>                  Allowed values: default, legacyjitx86, legacyjitx64, ryujitx64, dry, alljits, clr, mono, longrun
  --columns <COLUMNS>            Allowed values: mean, stderror, stddev, operationpersecond, min, q1, median, q3, max, allstatistics, place
  --exporters <EXPORTERS>        Allowed values: csv, csvmeasurements, html, markdown, stackoverflow, github, plain, rplot, json
  --diagnosers <DIAGNOSERS>      Allowed values:
  --analysers <ANALYSERS>        Allowed values: environment
  --validators <VALIDATORS>      Allowed values: baseline, jitOptimizations, jitOptimizationsFailOnError
  --loggers <LOGGERS>            Allowed values:
```

With 0.9.7:

```
>dotnet run -c Release -- --help
[... build bits ...]

BenchmarkDotNet v0.9.7
Options:
Unhandled Exception: System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at BenchmarkDotNet.Running.BenchmarkSwitcher.DisplayOptions()
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args)
   at NodaTime.Benchmarks.Program.Main(String[] args) in c:\Users\skeet\Test\Projects\nodatime\src\NodaTime.Benchmarks\Program.cs:line 18
```

**Comment by mattwarren** [comment]
I've been able to repro this, so I'll put some code in BenchmarkDotNet to protect against it

Seems like something changed in RC2, I'm not sure why getting the console width is a problem though! I'll also raise a bug over on the CLI repo.

**Comment by mattwarren** [comment]
Seems like others have come across this problem, see https://github.com/dotnet/cli/issues/2780

**Comment by jskeet** [comment]
So did 0.9.6 not use the console width? Because 0.9.6 was working *with RC2*. (If the use of the console width is known to be new in 0.9.7, that's fine. If that area of code hasn't changed, there's something else going on...)

**Comment by mattwarren** [comment]
Yeah the Console width code was [only introduced in 0.9.7](https://github.com/PerfDotNet/BenchmarkDotNet/commit/7568c06e8647f0bc4e8d53d1a00c61b526ec0289), before that it didn't try to wrap it (I guess your 0.9.6 output above is from a console that is wider than the longest line)
