### ISSUE TITLE
Exception After Running Benchmark

### ISSUE THREAD

**Issue by JasonBock** [PerfDotNet/BenchmarkDotNet#93]
The code to reproduce this is here:

https://github.com/JasonBock/ImprovingPerformance

It's the StringBuilderVersusXml project. If I run it, I get this exception:

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=StatSummary: Sequence contains no elements
  Source=BenchmarkDotNet
  StackTrace:
       at BenchmarkDotNet.Mathematics.Statistics..ctor(IEnumerable`1 values)
       at BenchmarkDotNet.Running.BenchmarkRunner.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark benchmark, ILogger logger, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
       at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
       at StringBuilderVersusXml.Program.Main(String[] args) in M:\JasonBock\Personal\Code Projects\ImprovingPerformance\StringBuilderVersusXml\Program.cs:line 10
  InnerException:

**Comment by adamsitnik** [comment]
Hi @JasonBock !

I am able to reproduce your error. The problem is that the method that you are trying to execute is throwing an exception:

```
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Xml.Linq.dll

Additional information: This operation would create an incorrectly structured document.
```

**Comment by JasonBock** [comment]
Well, that would cause it :). It wasn't obvious in the exception message though, unless I missed it.

**Comment by adamsitnik** [comment]
Yes, you are right. We should give more detailed info on error.

**Comment by mattwarren** [comment]
@JasonBock/@adamsitnik how is this benchmark being run when the exception is hidden? 

I just tried a simple test with a benchmark that throws an exception:

``` csharp
[Benchmark]
public void ThrowAnError()
{
    throw new System.InvalidProgramException("An Error occured!!");
}
```

which is run from a console app, like so: 

``` csharp
static void Main(string[] args)
{
    Console.Out.WriteLine(BenchmarkRunner.Run<ThrowAnError>());
}
```

And when I ran it on the command line I got this:

![image](https://cloud.githubusercontent.com/assets/157298/13220560/c30dd89a-d96e-11e5-8b7e-e7c880ead186.png)

**Comment by adamsitnik** [comment]
As far as I remember here the problem was that first benchmark got executed and the second has failed. So there was a lot of things in output, which could be confusing.
